---
title: "Fields of study"
output:
  rmdformats::readthedown:
    self_contained: false
    includes:
      in_header: GA_Script.html
params:
  CIPS_codes: "nothing"
  field_data: "nothing"
  scorecard_field_aggregated: "nothing"
  
---

This has the number of degrees awarded in the most recent year available. You can click on a column to sort by it. Clicking on a number will go to the page with information on that field and degree level, including which colleges have recently awarded degrees in that field. You can also start typing in the search box to filter the table.

```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
source("_packages.R")
source("R/functions.R")
CIPS_codes <- params$CIPS_codes
field_data <- params$field_data
CIP_headers <- CIPS_codes[!duplicated(CIPS_codes$CIPFamilyName),]
CIP_content <- CIPS_codes[duplicated(CIPS_codes$CIPFamilyName),]
CIP_content <- CIP_content[order(nchar(CIP_content$CIPDefinition), decreasing=TRUE),]
CIP_content <- CIP_content[!base::duplicated(CIP_content$CIPTitle),]
field_data_wide <- field_data |> pivot_wider(names_from = Degree, values_from = c(`Degrees completed`, `Schools offering`), names_sep = ": ", values_fill=0)

field_data_merged <- left_join(field_data_wide, CIP_content, by=c("Field"="CIPTitle"))

CIP_headers_simpified <- CIP_headers %>% dplyr::mutate(CIPFamilyHeaderName=CIPFamilyName, CIPFamilyHeaderDefinition=CIPDefinition) %>% dplyr::select(CIPFamilyHeaderName, CIPFamilyHeaderDefinition)
field_data_merged_with_headers <- left_join(field_data_merged, CIP_headers_simpified, by=c("CIPFamilyName"="CIPFamilyHeaderName"))


conversions <- read.csv("data/AbbreviateFieldNames.csv")
field_data_merged_with_headers <- left_join(field_data_merged_with_headers, conversions, by=c("CIPFamilyName"="CIPFamilyName")) 


field_data_merged_with_headers <- field_data_merged_with_headers |> 
	dplyr::rename( Definition = CIPDefinition, Family=CIPFamilyName, `Family Definition` = CIPFamilyHeaderDefinition) |> 
	dplyr::select(Area, Field, `Degrees completed: Bachelors`, `Degrees completed: Masters`, `Degrees completed: Doctorate`, `Degrees completed: Associates`, `Degrees completed: Certificate`, Definition) |> dplyr::arrange(desc(`Degrees completed: Bachelors`))
colnames(field_data_merged_with_headers) <- gsub("Degrees completed: ", "", colnames(field_data_merged_with_headers))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}


#field_family_level <- field_data_merged_with_headers |> group_by(Family) %>% summarize(`Total Bachelors` = sum(`Bachelors`), `Total Masters` = sum(`Masters`), `Total Doctorates` = sum(`Doctorate`), `Total Associates` = sum(`Associates`), `Total Certificates` = sum(`Certificate`)) |> dplyr::arrange(desc(`Total Bachelors`))

field_data_merged_with_headers$BachelorsURL <- URLEncodeTotal(paste0("majors_","Bachelors", "_",  gsub('/', "_",gsub(",", "_", gsub(" ", "", field_data_merged_with_headers$Field)))))

field_data_merged_with_headers$MastersURL <- URLEncodeTotal(paste0("majors_","Masters", "_",  gsub('/', "_",gsub(",", "_", gsub(" ", "", field_data_merged_with_headers$Field)))))

field_data_merged_with_headers$DoctorateURL <- URLEncodeTotal(paste0("majors_","Doctorate", "_",  gsub('/', "_",gsub(",", "_", gsub(" ", "", field_data_merged_with_headers$Field)))))

field_data_merged_with_headers$AssociatesURL <- URLEncodeTotal(paste0("majors_","Associates", "_",  gsub('/', "_",gsub(",", "_", gsub(" ", "", field_data_merged_with_headers$Field)))))

field_data_merged_with_headers$CertificateURL <- URLEncodeTotal(paste0("majors_","Certificate", "_",  gsub('/', "_",gsub(",", "_", gsub(" ", "", field_data_merged_with_headers$Field)))))

field_data_merged_with_headers$Field <- gsub(", General$", "", field_data_merged_with_headers$Field) #just to save on space

degree_vector <- c("Bachelors", "Masters", "Doctorate", "Associates", "Certificate")
gender_vector <- c("all", "men", "women")

for (degree in degree_vector) {
	for (gender in gender_vector) {
		field_data_merged_with_headers[[paste0(degree, " ", gender, " earnings 5 yr") ]] <- NA

		
		field_data_merged_with_headers[[paste0(degree, " ", gender, " earnings 1 yr") ]] <- NA
		for(i in sequence(nrow(field_data_merged_with_headers))) {
	
			try(field_data_merged_with_headers[i, paste0(degree, " ", gender, " earnings 5 yr") ] <- scorecard_field_aggregated[which(scorecard_field_aggregated$CIPDESC==field_data_merged_with_headers$Field[i] & scorecard_field_aggregated$CREDDESC==degree), paste0("Earnings 5 year ", gender)], silent=TRUE)
			
			
			try(field_data_merged_with_headers[i, paste0(degree, " ", gender, " earnings 1 yr") ] <- scorecard_field_aggregated[which(scorecard_field_aggregated$CIPDESC==field_data_merged_with_headers$Field[i] & scorecard_field_aggregated$CREDDESC==degree), paste0("Earnings 1 year ", gender)], silent=TRUE)
			
		}
	}
}

field_data_merged_with_headers <- field_data_merged_with_headers |> dplyr::select("Area", "Field", 

"Bachelors", "Bachelors all earnings 1 yr", "Bachelors all earnings 5 yr", 

"Masters", "Masters all earnings 1 yr", "Masters all earnings 5 yr",

"Doctorate", "Doctorate all earnings 1 yr", "Doctorate all earnings 5 yr",
 
"Associates", "Associates all earnings 1 yr", "Associates all earnings 5 yr", 

"Certificate", "Certificate all earnings 1 yr", "Certificate all earnings 5 yr",

"Definition",



"Bachelors women earnings 1 yr", "Bachelors men earnings 1 yr",
"Bachelors women earnings 5 yr",  "Bachelors men earnings 5 yr", 

"Masters women earnings 1 yr", "Masters men earnings 1 yr",
"Masters women earnings 5 yr",  "Masters men earnings 5 yr",

"Doctorate women earnings 1 yr", "Doctorate men earnings 1 yr",
"Doctorate women earnings 5 yr", "Doctorate men earnings 5 yr",

"Associates women earnings 1 yr", "Associates men earnings 1 yr",
"Associates women earnings 5 yr",  "Associates men earnings 5 yr", 

"Certificate women earnings 1 yr", "Certificate men earnings 1 yr",
"Certificate women earnings 5 yr",  "Certificate men earnings 5 yr", 

"BachelorsURL", "MastersURL", "DoctorateURL", "AssociatesURL", "CertificateURL")

#reactable(
#  field_family_level,
#  details = function(index) {
#    degrees <- filter(field_data_merged_with_headers, Family==field_family_level$Family[index]) |> dplyr::select(-Family)
#    tbl <- reactable(degrees, outlined = TRUE, highlight = TRUE, fullWidth = FALSE)
#    htmltools::div(style = list(margin = "12px 45px"), tbl)
#  },
#  onClick = "expand",
#  rowStyle = list(cursor = "pointer")
#)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
reactable(
  field_data_merged_with_headers,
  searchable = TRUE,
  highlight = TRUE,
  striped = TRUE,
  defaultColDef = colDef(
	show = TRUE
  ),
	columns = list(
		Area = colDef(minWidth = 100, show=TRUE),
		Field = colDef(minWidth = 200, show=TRUE),
		Bachelors = colDef(html = TRUE, format=colFormat(separators=TRUE), show=TRUE, cell = JS('
			function(cellInfo) {
			// Render as a link
			const url = `${cellInfo.row["BachelorsURL"]}.html`
			return `<a href="${url}" target="_blank">${cellInfo.value}</a>`
			}
		')
		),
		BachelorsURL = colDef(show=FALSE),
		MastersURL = colDef(show=FALSE),
		DoctorateURL = colDef(show=FALSE),
		AssociatesURL = colDef(show=FALSE),
		CertificateURL = colDef(show=FALSE),	
		`Bachelors all earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Bachelors all earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Masters all earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Masters all earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Doctorate all earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Doctorate all earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Associates all earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Associates all earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Certificate all earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Certificate all earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Bachelors women earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Bachelors women earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Masters women earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Masters women earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Doctorate women earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Doctorate women earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Associates women earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Associates women earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Certificate women earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Certificate women earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Bachelors men earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Bachelors men earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Masters men earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Masters men earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Doctorate men earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Doctorate men earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Associates men earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Associates men earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Certificate men earnings 1 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
		`Certificate men earnings 5 yr` = colDef(show=TRUE, format=colFormat(separators=TRUE, currency="USD", digits=0)),
	

		Masters = colDef(html = TRUE, format=colFormat(separators=TRUE), show=TRUE, cell = JS('
			function(cellInfo) {
			// Render as a link
			const url = `${cellInfo.row["MastersURL"]}.html`
			return `<a href="${url}" target="_blank">${cellInfo.value}</a>`
			}
		')
		),	
		Doctorate = colDef(html = TRUE, format=colFormat(separators=TRUE), show=TRUE, cell = JS('
			function(cellInfo) {
			// Render as a link
			const url = `${cellInfo.row["DoctorateURL"]}.html`
			return `<a href="${url}" target="_blank">${cellInfo.value}</a>`
			}
		')
		),	
		Associates = colDef(html = TRUE, format=colFormat(separators=TRUE), show=TRUE, cell = JS('
			function(cellInfo) {
			// Render as a link
			const url = `${cellInfo.row["AssociatesURL"]}.html`
			return `<a href="${url}" target="_blank">${cellInfo.value}</a>`
			}
		')
		),
		Certificate = colDef(html = TRUE, format=colFormat(separators=TRUE), show=TRUE, cell = JS('
			function(cellInfo) {
			// Render as a link
			const url = `${cellInfo.row["CertificateURL"]}.html`
			return `<a href="${url}" target="_blank">${cellInfo.value}</a>`
			}
		')
		),
		Definition = colDef(minWidth = 500, show=TRUE)
	) 
)
```

